ByteartRetail.Web/Controllers/LayoutController.cs
using ByteartRetail.DataObjects;
using ByteartRetail.Infrastructure.Communication;
using ByteartRetail.Infrastructure.Config;
using ByteartRetail.ServiceContracts;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ByteartRetail.Web.Controllers
{
    [HandleError]
    public class LayoutController : ControllerBase
    {
        #region Shared Layout Partial View Actions
        public ActionResult CategoriesPartial()
        {
            using (ServiceProxy<IProductService> proxy = new ServiceProxy<IProductService>())
            {
                var categories = proxy.Channel.GetCategories(QuerySpec.Empty);
                return PartialView(categories);
            }
        }

        public ActionResult _LoginPartial()
        {
            if (User.Identity.IsAuthenticated)
            {
                using (ServiceProxy<IOrderService> proxy = new ServiceProxy<IOrderService>())
                {
                    ViewBag.ShoppingCartItems = proxy.Channel.GetShoppingCartItemCount(UserID);
                }
            }
            return PartialView();
        }

        public ActionResult FeaturedProductsPartial()
        {
            using (ServiceProxy<IProductService> proxy = new ServiceProxy<IProductService>())
            {
                var featuredProducts = proxy.Channel.GetFeaturedProducts(4);
                return PartialView(featuredProducts);
            }
        }

        public ActionResult ProductsPartial(string categoryID = null, bool? fromIndexPage = null, int pageNumber = 1)
        {
            using (ServiceProxy<IProductService> proxy = new ServiceProxy<IProductService>())
            {
                var numberOfProductsPerPage = ByteartRetailConfigurationReader.Instance.ProductsPerPage;
                var pagination = new Pagination { PageSize = numberOfProductsPerPage, PageNumber = pageNumber };
                ProductDataObjectListWithPagination productsWithPagination = null;
                if (string.IsNullOrEmpty(categoryID))
                    productsWithPagination = proxy.Channel.GetProductsWithPagination(pagination);
                else
                    productsWithPagination = proxy.Channel.GetProductsForCategoryWithPagination(new Guid(categoryID), pagination);
                if (fromIndexPage != null &&
                    !fromIndexPage.Value)
                {
                    if (string.IsNullOrEmpty(categoryID))
                        ViewBag.CategoryName = "所有商品";
                    else
                    {
                        var category = proxy.Channel.GetCategoryByID(new Guid(categoryID), QuerySpec.Empty);
                        ViewBag.CategoryName = category.Name;
                    }
                }
                else
                    ViewBag.CategoryName = null;
                ViewBag.CategoryID = categoryID;
                ViewBag.FromIndexPage = fromIndexPage;
                if (fromIndexPage == null || fromIndexPage.Value)
                    ViewBag.Action = "Index";
                else
                    ViewBag.Action = "Category";
                ViewBag.IsFirstPage = productsWithPagination.Pagination.PageNumber == 1;
                ViewBag.IsLastPage = productsWithPagination.Pagination.PageNumber == productsWithPagination.Pagination.TotalPages;
                return PartialView(productsWithPagination);
            }
        }
        #endregion

        
    }
}

ByteartRetail.Web/Views/Shared/CategoriesPartial.cshtml
@model ByteartRetail.DataObjects.CategoryDataObjectList

<table width="202" border="0" cellspacing="0" cellpadding="0">
    <tr>
        <td height="320" align="left" valign="top">
            <div class="category">
                <img src="/images/spacer.gif" alt="" width="30" height="19">商品分类<a href="http://daxnet.cnblogs.com/"><img src="/images/spacer.gif" alt="" width="10" height="10" border="0"></a></div>
            <div class="linkmenu">
                <img src="/images/spacer.gif" alt="" width="20" height="19"><span class="red">&bull;</span>&nbsp;&nbsp;<a href="http://daxnet.cnblogs.com/">@Html.ActionLink("所有商品", "Category", "Home", null, null)</a></div>
            @foreach(var item in Model)
            {
            <div class="linkmenu">
                <img src="/images/spacer.gif" alt="" width="20" height="19"><span class="red">&bull;</span>&nbsp;&nbsp;@Html.ActionLink(item.Name, "Category", "Home", new { categoryID = item.ID }, null)</div>
            }
        </td>
    </tr>
    <tr>
        <td height="26">&nbsp;</td>
    </tr>
    <tr>
        <td align="center"><a href="http://daxnet.cnblogs.com/">
            <img src="/images/banner.jpg" alt="" width="197" height="215" border="0"></a></td>
    </tr>
</table>

ByteartRetail.Web/Views/Shared/FeaturedProductsPartial.cshtml
@using ByteartRetail.DataObjects;
@using ByteartRetail.Web;
@model ByteartRetail.DataObjects.ProductDataObjectList

<table width="774" border="0" cellspacing="0" cellpadding="0">
    <tr>
        <td height="40" class="popular">
            <img src="/images/spacer.gif" alt="" width="27" height="19"><span class="popular_text">特色商品推荐</span></td>
    </tr>
    <tr>
        <td height="138" valign="top" class="popular_center">
            <table width="774" border="0" cellpadding="0" cellspacing="0">
                <tr>
                    <td width="15">&nbsp;</td>
                    <td width="743">
                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                            <tr>
                                @for (int i = 0; i < Model.Count; i++)
                                {
                                    var model = Model[i];
                                    <td width="21%" height="148" align="center">
                                        <a href="@Url.Action("Product", "Home", new { id = model.ID})">
                                            <img src="@string.Format(Url.Content("~/Images/Products/{0}"), model.ImageUrl)" alt="" width="140" height="117" border="0">
                                        </a>
                                        <br>
                                        <span class="style7"><a href="@Url.Action("Product", "Home", new { id = model.ID})">@Html.Encode(model.Name)</a></span></td>
                                    if (i != Model.Count - 1)
                                    {
                                    <td width="2%" align="center">
                                        <img src="/images/op.jpg" width="14" height="117">
                                    </td>
                                    }
                                }
                            </tr>
                        </table>
                    </td>
                    <td width="16">&nbsp;</td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td valign="top">
            <img src="/images/close.gif" alt="" width="774" height="9"></td>
    </tr>
</table>

ByteartRetail.Web/Views/Shared/ProductsPartial.cshtml
@using ByteartRetail.DataObjects;
@using ByteartRetail.Web;
@model ByteartRetail.DataObjects.ProductDataObjectListWithPagination

@if (ViewBag.CategoryName != null)
{
    <h2>商品分类：@ViewBag.CategoryName</h2>
}
<table width="774" border="0" cellspacing="0" cellpadding="0">

    <tr>
        <td height="479">&nbsp;</td>
        <td align="left" valign="top" width="100%">
            @{
                 
                if (Model.ProductDataObjectList.Count > 0)
                {
                    for (int i = 0; i < Model.ProductDataObjectList.Count; i++)
                    {
                        var model = Model.ProductDataObjectList[i];
                <table width="207" height="234" border="0" cellpadding="0" cellspacing="0" class="productleft_top">
                    <tr>
                        <td align="left" valign="top">
                            <table width="222" border="0" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td height="200" valign="top">
                                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                            <tr>
                                                <td height="45"><span class="product_name">@Html.ActionLink(model.Name, "Product", "Home", new { id = model.ID }, null)</span></td>
                                            </tr>
                                            <tr>
                                                <td height="147" align="center"><a href="@Url.Action("Product", "Home", new { id = model.ID })">
                                                    <img src="@Url.Content(string.Format("~/Images/Products/{0}", model.ImageUrl))" alt="" width="175" height="144" border="0"></a></td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                                <tr>
                                    <td height="35">
                                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                            <tr>
                                                <td width="24%" height="24"><span class="style7"><a href="@Url.Action("Product", "Home", new { id = model.ID })" id="blue1">详细信息</a></span></td>
                                                <td width="5%">&nbsp;</td>
                                                <td width="15%" height="24"><span class="style7"><a href="@Url.Action("AddToCart", "Home", new { productID = model.ID, items = "1" })" id="blue1">购买</a></span></td>
                                                <td width="5%">&nbsp;</td>
                                                <td width="51%" class="price">@Html.Encode(string.Format("{0:N2} {1}", model.UnitPrice, "元"))</td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
                    }
                    <table style="width: 100%">
                        <tr>
                            <td style="text-align: right; font-size: 12px;">
                                @Html.Encode(string.Format("第{0}页，共{1}页", Model.Pagination.PageNumber, Model.Pagination.TotalPages))
                                &nbsp;
                                @if (!ViewBag.IsFirstPage)
                                {
                                    @Html.ActionLink("首页", (string)ViewBag.Action, "Home", new { categoryID = ViewBag.CategoryID, pageNumber = 1 }, new { id="blue1" })
                                }
                                else
                                {
                                    @Html.Encode("首页")
                                }
                                &nbsp;
                                @if (!ViewBag.IsFirstPage)
                                {
                                    @Html.ActionLink("上页", (string)ViewBag.Action, "Home", new { categoryID = ViewBag.CategoryID, pageNumber = Model.Pagination.PageNumber - 1}, new { id="blue1" })
                                }
                                else
                                {
                                    @Html.Encode("上页")
                                }
                                &nbsp;
                                @if (!ViewBag.IsLastPage)
                                {
                                    @Html.ActionLink("下页", (string)ViewBag.Action, "Home", new { categoryID = ViewBag.CategoryID, pageNumber = Model.Pagination.PageNumber + 1},  new { id="blue1" })
                                }
                                else
                                {
                                    @Html.Encode("下页")
                                }
                                &nbsp;
                                @if (!ViewBag.IsLastPage)
                                {
                                    @Html.ActionLink("尾页", (string)ViewBag.Action, "Home", new { categoryID = ViewBag.CategoryID, pageNumber = Model.Pagination.TotalPages},  new { id="blue1" })
                                }
                                else
                                {
                                    @Html.Encode("尾页")
                                }
                            </td>
                        </tr>
                    </table>
                }
                else
                {
                <h4>没有找到任何商品</h4>
                }
            }

        </td>
        <td>&nbsp;</td>
    </tr>
</table>

ByteartRetail.Web/Views/Shared/_Layout.cshtml
@using ByteartRetail.Web;
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Byteart Retail</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/Site.css")" />
    <link type="text/css" href="@Url.Content("~/Content/uploadify.css")" rel="stylesheet" />
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-ui-1.8.23.custom.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/hoverIntent.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/superfish.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.uploadify.min.js")"></script>
    <script type="text/javascript">
        // initialise plugins
        jQuery(function () {
            jQuery('ul.sf-menu').superfish();
        });

    </script>
</head>
<body>
    <table width="996" border="0" cellspacing="0" cellpadding="0" align="center">
        <tr>
            <td height="607" valign="top">
                <table width="996" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                        <td width="300" height="55" class="logo"></td>
                        <td width="480" class="menu">
                            <ul class="sf-menu">
                                <li>@Html.ActionLink("首页", "Index", "Home")</li>
                                @if (User.Identity.IsAuthenticated)
                                {
                                <li>@Html.ActionLink("我的", "Account", "Account")
                                    <ul>
                                        <li>@Html.ActionLink("订单", "SalesOrders", "Home")</li>
                                        <li>@Html.ActionLink("账户", "Account", "Account")</li>
                                        <li>@Html.ActionLink("购物篮", "ShoppingCart", "Home")</li>
                                    </ul>
                                </li>
                                }
                                <li>@Html.ActionLink("注册", "Register", "Account")</li>
                                @if (User.Identity.IsAuthenticated)
                                {
                                    <li>@Html.ActionLinkWithPermission("管理", "Administration", "Admin", PermissionKeys.Administrators | PermissionKeys.Buyers | PermissionKeys.SalesReps)
                                        <ul>
                                            <li>@Html.ActionLinkWithPermission("销售订单管理", "SalesOrders", "Admin", PermissionKeys.Administrators | PermissionKeys.SalesReps)</li>
                                            <li>@Html.ActionLinkWithPermission("商品分类管理", "Categories", "Admin", PermissionKeys.Administrators | PermissionKeys.Buyers)</li>
                                            <li>@Html.ActionLinkWithPermission("商品信息管理", "Products", "Admin", PermissionKeys.Administrators | PermissionKeys.Buyers)</li>
                                            <li>@Html.ActionLinkWithPermission("用户账户管理", "UserAccounts", "Admin", PermissionKeys.Administrators)</li>
                                            <li>@Html.ActionLinkWithPermission("用户角色管理", "Roles", "Admin", PermissionKeys.Administrators)</li>
                                        </ul>
                                    </li>
                                }
                                <li>@Html.ActionLink("关于", "About", "Home")
                                    <ul>
                                        <li>@Html.ActionLink("Byteart Retail 项目", "About", "Home")</li>
                                        <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
                                    </ul>
                                </li>
                            </ul>
                        </td>
                        <td width="216" class="menu">
                            @{Html.RenderAction("_LoginPartial", "Layout");}
                        </td>
                    </tr>
                </table>
                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                        <td width="100%" height="10px" />
                    </tr>
                </table>
                <table width="996" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                        <td>
                            <img src="/images/header.jpg" alt="" width="996" height="300" border="0"></td>
                    </tr>
                </table>
                <table width="996" border="0" cellspacing="0" cellpadding="0">
                    <tr align="left" valign="top">
                        <td width="202" height="334">
                            @{Html.RenderAction("CategoriesPartial", "Layout");}
                        </td>
                        <td width="20">&nbsp;</td>
                        <td width="774">

                            <table width="774" border="0" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td>@RenderBody()</td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
                <table width="996" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                        <td>
                            <img src="/images/footer.jpg" alt="" width="996" height="5"></td>
                    </tr>
                    <tr>
                        <td height="76">
                            <table width="996" border="0" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td width="329" height="78" align="right"><span class="category"><a href="http://daxnet.cnblogs.com/">
                                        <img src="/images/spacer.gif" alt="" width="10" height="10" border="0"></a></span><img src="@Url.Content("~/Images/byteartretail_logo_trans.png")" alt="" border="0"></a></td>
                                    <td width="14">&nbsp;</td>
                                    <td width="653"><span class="style7">@Html.ActionLink("主页", "Index", "Home")&nbsp; | &nbsp;&nbsp;@Html.ActionLink("所有分类", "Category", "Home", null, null)&nbsp;&nbsp;|&nbsp;&nbsp; @Html.ActionLink("我的账户", "Account", "Account")&nbsp;&nbsp; |&nbsp;&nbsp; @Html.ActionLink("联系我们", "Contact", "Home")&nbsp;&nbsp; |&nbsp;&nbsp;@Html.ActionLink("关于本站", "About", "Home")</span><br>
                                        版权所有 &copy; 2011-2012, Byteart Retail, 保留所有权利。 </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>

            </td>
        </tr>
    </table>
    @RenderSection("scripts", false)
</body>
</html>